### ISSUE TITLE
request support for .zip file

### ISSUE THREAD

**Issue by lukemin** [LeversonCarlos/ComicsShelf#82]
I have 70g mages in 555 zip files, and I synchronized them to one drive, It is hard for me to change the name. so would you  like add .zip file?

**Comment by LeversonCarlos** [comment]
Hi there and really sorry for this huge delay... 
Point is, we search for the files (using cbz extentions) and then we assume that a list of imagens are inside it... So we extractit and use imagens parsers on the zip entries.
If we open this restrictions for zip extentions, many, many people should start facing errors when the app opens zips that has other things inside and tha image parsers starts to fail.
Hope you understand.

**Comment by LeversonCarlos** [comment]
Closing for now
